// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FuncArgument } from "./FuncArgument";
import type { FunctionTags } from "./FunctionTags";

export type Function = { name: string, arguments: Array<FuncArgument>, return_type: string | null, tags: Array<FunctionTags>, description: string, body: string, parsed_body: string, language: string | null, complete: boolean, };
