// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacroArgument } from "./MacroArgument";

export type MacroFunc = { name: string, arguments: Array<MacroArgument>, description: string, body: string, parsed_body: string, used_arguments: Array<string>, };
