// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Function } from "./Function";
import type { MacroFunc } from "./MacroFunc";
import type { Migration } from "./Migration";
import type { MigrationGroup } from "./MigrationGroup";

export type MigrationFile = { file_path: string, file_name: string, file_content: string, migrations: Array<Migration>, migration_groups: Array<MigrationGroup>, macros: Array<MacroFunc>, functions: Array<Function>, sqlx_version: string | null, };
