// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MigrationDependency } from "./MigrationDependency";
import type { MigrationTags } from "./MigrationTags";

export type Migration = { name: string, version: string, description: string, sql: string, dependencies: Array<MigrationDependency>, tags: Array<MigrationTags>, };
