// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Migration } from "./Migration";
import type { MigrationDependency } from "./MigrationDependency";
import type { MigrationTags } from "./MigrationTags";

export type MigrationGroup = { name: string, version: string, description: string, migrations: Array<Migration>, groups: Array<MigrationGroup>, dependencies: Array<MigrationDependency>, current_group_index: number, tags: Array<MigrationTags>, };
