#[derive(Debug, Clone)]
pub struct ParseError {
    pub kind: ParseErrorKind,
    pub message: String,
    pub line: usize,
    pub column: usize,
}

#[derive(Debug, Clone)]
pub enum ParseErrorKind {
    MissingArgumentType,
    InvalidArgumentFormat,
    MissingArgument(String),
    UnknownTag(String),
    UnexpectedEndOfFile(usize),
    UnexpectedMigrationStart,
    UnexpectedMigrationEnd,
    MissingMigrationName,
    MissingMigrationGroupName,
    UnexpectedMacroStart,
    UnexpectedMacroEnd,
    MissingMacroName,
    UnexpectedFunctionStart,
    UnexpectedFunctionEnd,
    UnexpectedMigrationGroupStart,
    UnexpectedMigrationGroupEnd,
    MissingFunctionName,
    NuclearWithoutContext,
    TagsWithoutContext,
    RollbackWithoutContext,
    ParametersWithoutContext,
    ReturnsWithoutContext,
    DependsWithoutContext,
    DescriptionWithoutContext,
    MacroCallWithoutContext,
    SqlWithoutContext,
    MissingReturnType,
    MissingTags,
    MissingParameters,
    InvalidDependencyFormat(String),
    NestedMigration(usize),
    MigrationNotClosed,
    MigrationGroupNotClosed,
    MacroNotClosed,
    FunctionNotClosed,
    EndMigrationWithoutStart(usize),
}
